title: Shmully Wolfson
description: My Personal Tech Blogings
author: Shmully Wolfson
github: https://github.com/shmuwol
about: I am student at Flairon School - Learn.co
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/shmuwol
    - text: XML Feed
      url: /feed.xml
url: "https://shmuwol.github.io"
baseurl: ""
paginate: 20
per_page: 20
gems: [jekyll-paginate]
markdown: kramdown
