# Site settings
title: Shmully Wolfson
header-img: img/home-bg.png
email: shmullywolfson@gmail.com
copyright_name: Shmuwol
description: > # this means to ignore newlines until "baseurl:"
  Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: shmullywolfson
github_username:  Shmuwol
learn_profile: Shmuwol
email_username: shmullywolfson@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
